import type { NextPage } from 'next';
import Head from 'next/head';
import { Center, Text, Heading, Stack } from '@chakra-ui/react';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Waver</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center h="100vh">
				<Stack>
					<Heading>Wave at me 👋🏿</Heading>
					<Text textAlign="center">Still in production 🚧</Text>
				</Stack>
			</Center>
		</>
	);
};

export default Home;
