declare let window: any;
import type { NextPage } from 'next';
import Head from 'next/head';
import { Center, Text, Heading, Stack, Box, HStack } from '@chakra-ui/react';
import { useEffect, useState } from 'react';
import { FaWallet } from 'react-icons/fa';

const Home: NextPage = () => {
	const [account, setAccount] = useState('');

	const checkIfWalletIsConnected = async () => {
		const { ethereum } = window;

		if (!ethereum) {
			console.log('Make sure you have metamask!');
			return;
		} else {
			console.log('We have the ethereum object', ethereum);
		}
		const accounts = await ethereum.request({ method: 'eth_accounts' });

		if (accounts.length !== 0) {
			const account = accounts[0];
			console.log('Found an authorized account:', account);
			setAccount(account);
		} else {
			console.log('No authorized account found');
		}
	};

	const connectWallet = async () => {
		try {
			const { ethereum } = window;

			if (!ethereum) {
				alert('Get MetaMask!');
				return;
			}

			const accounts = await ethereum.request({
				method: 'eth_requestAccounts',
			});

			console.log('Connected', accounts[0]);
			setAccount(accounts[0]);
		} catch (error) {
			console.log(error);
		}
	};

	useEffect(() => {
		checkIfWalletIsConnected();
	}, []);

	return (
		<>
			<Head>
				<title>Waver</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center h="100vh" w="100vw" pos="relative">
				<HStack
					pos="absolute"
					top="12"
					right="12"
					userSelect="none"
					border="1px"
					rounded="full"
					px="2"
					py="1"
					color="#ee6002"
					bg="#fff2df"
				>
					<FaWallet />
					<Text fontSize="sm">
						{account.slice(0, 4)}...{account.slice(-4)}
					</Text>
				</HStack>
				<Stack>
					<Heading>Wave at me 👋🏿</Heading>
					<Text textAlign="center">Connect your wallet to continue</Text>
					{!account && (
						<Box
							as="button"
							type="button"
							rounded="xl"
							py="2"
							px="6"
							cursor="pointer"
							fontWeight="medium"
							w="fit-content"
							color="#ee6002"
							bg="#fff2df"
							onClick={connectWallet}
						>
							Connect your wallet
						</Box>
					)}
				</Stack>
			</Center>
		</>
	);
};

export default Home;
