declare let window: any;
import type { NextPage } from 'next';
import Head from 'next/head';
import { Center, Text, Heading, Stack, Button } from '@chakra-ui/react';
import { ethers } from 'ethers';
import abi from '@/constants/WavePortal.json';

const Home: NextPage = () => {
	const contractAddress = '0x64b8c44420E1Df13A27bBe3F30E8dEF3e485443f';
	const contractABI = abi.abi;

	const wave = async () => {
		try {
			const { ethereum } = window;

			if (ethereum) {
				const provider = new ethers.providers.Web3Provider(ethereum);

				const signer = provider.getSigner();
				const wavePortalContract = new ethers.Contract(
					contractAddress,
					contractABI,
					signer
				);

				let count = await wavePortalContract.getTotalWaves();
				console.log('Retrieved total wave count...', count.toNumber());

				const waveTxn = await wavePortalContract.wave();
				console.log({ waveTxn });

				console.log('Mining...', waveTxn.hash);

				await waveTxn.wait();
				console.log('Mined -- ', waveTxn.hash);

				count = await wavePortalContract.getTotalWaves();
				console.log('Retrieved total wave count...', count.toNumber());
			} else {
				console.log("Ethereum object doesn't exist!");
			}
		} catch (error) {
			console.log(error);
		}
	};

	return (
		<>
			<Head>
				<title>Waver</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center h="100vh" w="100vw" pos="relative">
				<Stack>
					<Heading>Wave at me 👋🏿</Heading>
					<Text textAlign="center">Connect your wallet to continue</Text>
					<Button onClick={wave}>Wave at me</Button>
				</Stack>
			</Center>
		</>
	);
};

export default Home;
